/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => LoansPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// locales.ts
var translations = {
  ru: {
    pluginName: "\u0423\u0447\u0435\u0442 \u043A\u0440\u0435\u0434\u0438\u0442\u043E\u0432",
    addLoan: "\u0414\u043E\u0431\u0430\u0432\u0438\u0442\u044C \u043A\u0440\u0435\u0434\u0438\u0442",
    editLoan: "\u0420\u0435\u0434\u0430\u043A\u0442\u0438\u0440\u043E\u0432\u0430\u0442\u044C \u043A\u0440\u0435\u0434\u0438\u0442",
    deleteLoan: "\u0423\u0434\u0430\u043B\u0438\u0442\u044C \u043A\u0440\u0435\u0434\u0438\u0442",
    save: "\u0421\u043E\u0445\u0440\u0430\u043D\u0438\u0442\u044C",
    cancel: "\u041E\u0442\u043C\u0435\u043D\u0430",
    close: "\u0417\u0430\u043A\u0440\u044B\u0442\u044C",
    back: "\u041D\u0430\u0437\u0430\u0434",
    yes: "\u0414\u0430",
    no: "\u041D\u0435\u0442",
    loanName: "\u041D\u0430\u0437\u0432\u0430\u043D\u0438\u0435 \u043A\u0440\u0435\u0434\u0438\u0442\u0430",
    totalAmount: "\u0421\u0443\u043C\u043C\u0430 \u043A\u0440\u0435\u0434\u0438\u0442\u0430",
    interestRate: "\u041F\u0440\u043E\u0446\u0435\u043D\u0442\u043D\u0430\u044F \u0441\u0442\u0430\u0432\u043A\u0430 (% \u0433\u043E\u0434.)",
    termMonths: "\u0421\u0440\u043E\u043A (\u043C\u0435\u0441\u044F\u0446\u0435\u0432)",
    startDate: "\u0414\u0430\u0442\u0430 \u043D\u0430\u0447\u0430\u043B\u0430",
    paymentType: "\u0422\u0438\u043F \u043F\u043B\u0430\u0442\u0435\u0436\u0430",
    paymentTypeAnnuity: "\u0410\u043D\u043D\u0443\u0438\u0442\u0435\u0442\u043D\u044B\u0439",
    paymentTypeDifferentiated: "\u0414\u0438\u0444\u0444\u0435\u0440\u0435\u043D\u0446\u0438\u0440\u043E\u0432\u0430\u043D\u043D\u044B\u0439",
    currency: "\u0412\u0430\u043B\u044E\u0442\u0430",
    notes: "\u0417\u0430\u043C\u0435\u0442\u043A\u0438",
    payments: "\u041F\u043B\u0430\u0442\u0435\u0436\u0438",
    paymentDate: "\u0414\u0430\u0442\u0430",
    paymentAmount: "\u0421\u0443\u043C\u043C\u0430",
    principal: "\u041E\u0441\u043D\u043E\u0432\u043D\u043E\u0439 \u0434\u043E\u043B\u0433",
    interest: "\u041F\u0440\u043E\u0446\u0435\u043D\u0442\u044B",
    status: "\u0421\u0442\u0430\u0442\u0443\u0441",
    statusPending: "\u043E\u0436\u0438\u0434\u0430\u0435\u0442",
    statusPaid: "\u043E\u043F\u043B\u0430\u0447\u0435\u043D",
    statusOverdue: "\u043F\u0440\u043E\u0441\u0440\u043E\u0447\u0435\u043D",
    paidAmount: "\u0424\u0430\u043A\u0442\u0438\u0447\u0435\u0441\u043A\u0438 \u0443\u043F\u043B\u0430\u0447\u0435\u043D\u043D\u0430\u044F \u0441\u0443\u043C\u043C\u0430",
    paidDate: "\u0414\u0430\u0442\u0430 \u043E\u043F\u043B\u0430\u0442\u044B",
    markAsPaid: "\u041E\u0442\u043C\u0435\u0442\u0438\u0442\u044C \u043E\u043F\u043B\u0430\u0442\u0443",
    overallStats: "\u041E\u0431\u0449\u0430\u044F \u0441\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043A\u0430",
    totalLoans: "\u0412\u0441\u0435\u0433\u043E \u043A\u0440\u0435\u0434\u0438\u0442\u043E\u0432",
    totalDebt: "\u041E\u0431\u0449\u0438\u0439 \u0434\u043E\u043B\u0433",
    totalPaid: "\u0412\u044B\u043F\u043B\u0430\u0447\u0435\u043D\u043E",
    totalOverpaid: "\u041F\u0435\u0440\u0435\u043F\u043B\u0430\u0442\u0430",
    remainingPrincipal: "\u041E\u0441\u0442\u0430\u0442\u043E\u043A \u0434\u043E\u043B\u0433\u0430",
    progress: "\u041F\u0440\u043E\u0433\u0440\u0435\u0441\u0441",
    nextPayment: "\u0421\u043B\u0435\u0434\u0443\u044E\u0449\u0438\u0439 \u043F\u043B\u0430\u0442\u0435\u0436",
    nextPaymentDate: "\u0414\u0430\u0442\u0430",
    nextPaymentAmount: "\u0421\u0443\u043C\u043C\u0430",
    actions: "\u0414\u0435\u0439\u0441\u0442\u0432\u0438\u044F",
    addNewLoan: "\u2795 \u0414\u043E\u0431\u0430\u0432\u0438\u0442\u044C \u043A\u0440\u0435\u0434\u0438\u0442",
    repaymentCalculator: "\u{1F9EE} \u041A\u0430\u043B\u044C\u043A\u0443\u043B\u044F\u0442\u043E\u0440 \u043F\u043E\u0433\u0430\u0448\u0435\u043D\u0438\u044F",
    refresh: "\u{1F504} \u041E\u0431\u043D\u043E\u0432\u0438\u0442\u044C",
    openLoansView: "\u041E\u0442\u043A\u0440\u044B\u0442\u044C \u043F\u0430\u043D\u0435\u043B\u044C \u0443\u0447\u0435\u0442\u0430 \u043A\u0440\u0435\u0434\u0438\u0442\u043E\u0432",
    markPaymentPaid: "\u041E\u0442\u043C\u0435\u0442\u0438\u0442\u044C \u043F\u043B\u0430\u0442\u0435\u0436 \u043A\u0430\u043A \u0432\u044B\u043F\u043E\u043B\u043D\u0435\u043D\u043D\u044B\u0439",
    calculatorTitle: "\u041A\u0430\u043B\u044C\u043A\u0443\u043B\u044F\u0442\u043E\u0440 \u0432\u044B\u0433\u043E\u0434\u043D\u043E\u0433\u043E \u043F\u043E\u0433\u0430\u0448\u0435\u043D\u0438\u044F",
    calculatorDescription: "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u0441\u0443\u043C\u043C\u0443, \u043A\u043E\u0442\u043E\u0440\u0443\u044E \u043C\u043E\u0436\u0435\u0442\u0435 \u043D\u0430\u043F\u0440\u0430\u0432\u0438\u0442\u044C \u043D\u0430 \u0434\u043E\u0441\u0440\u043E\u0447\u043D\u043E\u0435 \u043F\u043E\u0433\u0430\u0448\u0435\u043D\u0438\u0435:",
    enterAmount: "\u0421\u0443\u043C\u043C\u0430",
    calculate: "\u0420\u0430\u0441\u0441\u0447\u0438\u0442\u0430\u0442\u044C",
    recommendations: "\u0420\u0435\u043A\u043E\u043C\u0435\u043D\u0434\u0430\u0446\u0438\u0438:",
    loanToRepay: "\u041A\u0440\u0435\u0434\u0438\u0442",
    amountToRepay: "\u0421\u0443\u043C\u043C\u0430 \u043A \u043F\u043E\u0433\u0430\u0448\u0435\u043D\u0438\u044E",
    savedInterest: "\u042D\u043A\u043E\u043D\u043E\u043C\u0438\u044F \u043D\u0430 \u043F\u0440\u043E\u0446\u0435\u043D\u0442\u0430\u0445",
    newRemaining: "\u041D\u043E\u0432\u044B\u0439 \u043E\u0441\u0442\u0430\u0442\u043E\u043A",
    noActiveLoans: "\u041D\u0435\u0442 \u0430\u043A\u0442\u0438\u0432\u043D\u044B\u0445 \u043A\u0440\u0435\u0434\u0438\u0442\u043E\u0432 \u0434\u043B\u044F \u043F\u043E\u0433\u0430\u0448\u0435\u043D\u0438\u044F.",
    settingsTitle: "\u041D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0438 \u043F\u043B\u0430\u0433\u0438\u043D\u0430 \u0443\u0447\u0435\u0442\u0430 \u043A\u0440\u0435\u0434\u0438\u0442\u043E\u0432",
    storageFile: "\u0424\u0430\u0439\u043B \u0445\u0440\u0430\u043D\u0435\u043D\u0438\u044F \u0434\u0430\u043D\u043D\u044B\u0445",
    storageFileDesc: "JSON \u0444\u0430\u0439\u043B, \u0433\u0434\u0435 \u0445\u0440\u0430\u043D\u044F\u0442\u0441\u044F \u0434\u0430\u043D\u043D\u044B\u0435 \u043E \u043A\u0440\u0435\u0434\u0438\u0442\u0430\u0445",
    defaultCurrency: "\u0412\u0430\u043B\u044E\u0442\u0430 \u043F\u043E \u0443\u043C\u043E\u043B\u0447\u0430\u043D\u0438\u044E",
    defaultCurrencyDesc: "\u0412\u0430\u043B\u044E\u0442\u0430 \u0434\u043B\u044F \u043D\u043E\u0432\u044B\u0445 \u043A\u0440\u0435\u0434\u0438\u0442\u043E\u0432 (RUB, USD, EUR \u0438 \u0442.\u0434.)",
    showNotifications: "\u0423\u0432\u0435\u0434\u043E\u043C\u043B\u0435\u043D\u0438\u044F",
    showNotificationsDesc: "\u041F\u043E\u043A\u0430\u0437\u044B\u0432\u0430\u0442\u044C \u0443\u0432\u0435\u0434\u043E\u043C\u043B\u0435\u043D\u0438\u044F \u043E \u043F\u0440\u043E\u0441\u0440\u043E\u0447\u0435\u043D\u043D\u044B\u0445 \u043F\u043B\u0430\u0442\u0435\u0436\u0430\u0445",
    autoCalculatePayments: "\u0410\u0432\u0442\u043E\u0440\u0430\u0441\u0447\u0435\u0442 \u043F\u043B\u0430\u0442\u0435\u0436\u0435\u0439",
    autoCalculatePaymentsDesc: "\u0410\u0432\u0442\u043E\u043C\u0430\u0442\u0438\u0447\u0435\u0441\u043A\u0438 \u043F\u0435\u0440\u0435\u0441\u0447\u0438\u0442\u044B\u0432\u0430\u0442\u044C \u0433\u0440\u0430\u0444\u0438\u043A \u043F\u043B\u0430\u0442\u0435\u0436\u0435\u0439 \u043F\u0440\u0438 \u0438\u0437\u043C\u0435\u043D\u0435\u043D\u0438\u0438 \u043A\u0440\u0435\u0434\u0438\u0442\u0430",
    notificationOverdue: "\u0412\u043D\u0438\u043C\u0430\u043D\u0438\u0435: \u0443 \u0432\u0430\u0441 {count} \u043F\u0440\u043E\u0441\u0440\u043E\u0447\u0435\u043D\u043D\u044B\u0445 \u043F\u043B\u0430\u0442\u0435\u0436\u0435\u0439!",
    loanAdded: '\u041A\u0440\u0435\u0434\u0438\u0442 "{name}" \u0434\u043E\u0431\u0430\u0432\u043B\u0435\u043D',
    loanUpdated: '\u041A\u0440\u0435\u0434\u0438\u0442 "{name}" \u043E\u0431\u043D\u043E\u0432\u043B\u0435\u043D',
    loanDeleted: '\u041A\u0440\u0435\u0434\u0438\u0442 "{name}" \u0443\u0434\u0430\u043B\u0435\u043D',
    paymentMarkedPaid: "\u041F\u043B\u0430\u0442\u0435\u0436 \u043E\u0442\u043C\u0435\u0447\u0435\u043D \u043A\u0430\u043A \u0432\u044B\u043F\u043E\u043B\u043D\u0435\u043D\u043D\u044B\u0439",
    errorRequiredField: "\u042D\u0442\u043E \u043F\u043E\u043B\u0435 \u043E\u0431\u044F\u0437\u0430\u0442\u0435\u043B\u044C\u043D\u043E",
    errorInvalidNumber: "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u043A\u043E\u0440\u0440\u0435\u043A\u0442\u043D\u043E\u0435 \u0447\u0438\u0441\u043B\u043E",
    errorLoanNotFound: "\u041A\u0440\u0435\u0434\u0438\u0442 \u043D\u0435 \u043D\u0430\u0439\u0434\u0435\u043D",
    errorPaymentNotFound: "\u041F\u043B\u0430\u0442\u0435\u0436 \u043D\u0435 \u043D\u0430\u0439\u0434\u0435\u043D"
  },
  en: {
    pluginName: "Loans Tracker",
    addLoan: "Add Loan",
    editLoan: "Edit Loan",
    deleteLoan: "Delete Loan",
    save: "Save",
    cancel: "Cancel",
    close: "Close",
    back: "Back",
    yes: "Yes",
    no: "No",
    loanName: "Loan Name",
    totalAmount: "Total Amount",
    interestRate: "Interest Rate (% annual)",
    termMonths: "Term (months)",
    startDate: "Start Date",
    paymentType: "Payment Type",
    paymentTypeAnnuity: "Annuity",
    paymentTypeDifferentiated: "Differentiated",
    currency: "Currency",
    notes: "Notes",
    payments: "Payments",
    paymentDate: "Date",
    paymentAmount: "Amount",
    principal: "Principal",
    interest: "Interest",
    status: "Status",
    statusPending: "pending",
    statusPaid: "paid",
    statusOverdue: "overdue",
    paidAmount: "Paid Amount",
    paidDate: "Paid Date",
    markAsPaid: "Mark as Paid",
    overallStats: "Overall Statistics",
    totalLoans: "Total Loans",
    totalDebt: "Total Debt",
    totalPaid: "Total Paid",
    totalOverpaid: "Overpaid",
    remainingPrincipal: "Remaining Principal",
    progress: "Progress",
    nextPayment: "Next Payment",
    nextPaymentDate: "Date",
    nextPaymentAmount: "Amount",
    actions: "Actions",
    addNewLoan: "\u2795 Add Loan",
    repaymentCalculator: "\u{1F9EE} Repayment Calculator",
    refresh: "\u{1F504} Refresh",
    openLoansView: "Open Loans Panel",
    markPaymentPaid: "Mark Payment as Paid",
    calculatorTitle: "Optimal Repayment Calculator",
    calculatorDescription: "Enter the amount you can allocate for early repayment:",
    enterAmount: "Amount",
    calculate: "Calculate",
    recommendations: "Recommendations:",
    loanToRepay: "Loan",
    amountToRepay: "Amount to Repay",
    savedInterest: "Interest Saved",
    newRemaining: "New Remaining",
    noActiveLoans: "No active loans to repay.",
    settingsTitle: "Loans Tracker Plugin Settings",
    storageFile: "Storage File",
    storageFileDesc: "JSON file where loan data is stored",
    defaultCurrency: "Default Currency",
    defaultCurrencyDesc: "Currency for new loans (RUB, USD, EUR, etc.)",
    showNotifications: "Notifications",
    showNotificationsDesc: "Show notifications for overdue payments",
    autoCalculatePayments: "Auto-calculate Payments",
    autoCalculatePaymentsDesc: "Automatically recalculate payment schedule when loan changes",
    notificationOverdue: "Warning: you have {count} overdue payments!",
    loanAdded: 'Loan "{name}" added',
    loanUpdated: 'Loan "{name}" updated',
    loanDeleted: 'Loan "{name}" deleted',
    paymentMarkedPaid: "Payment marked as paid",
    errorRequiredField: "This field is required",
    errorInvalidNumber: "Enter a valid number",
    errorLoanNotFound: "Loan not found",
    errorPaymentNotFound: "Payment not found"
  }
};
function getObsidianLanguage() {
  var _a, _b;
  const appLang = ((_b = (_a = window.app) == null ? void 0 : _a.settings) == null ? void 0 : _b.language) || navigator.language || "en";
  return appLang.startsWith("ru") ? "ru" : "en";
}
function t(key, lang, params) {
  let text = translations[lang][key];
  if (params) {
    Object.entries(params).forEach(([k, v]) => {
      text = text.replace(`{${k}}`, String(v));
    });
  }
  return text;
}

// main.ts
var DEFAULT_SETTINGS = {
  storageFile: "loans-data.json",
  defaultCurrency: "RUB",
  showNotifications: true,
  autoCalculatePayments: true
};
var LoansPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.loans = [];
    this.payments = [];
    this.language = "en";
  }
  async onload() {
    await this.loadSettings();
    await this.loadData();
    this.language = getObsidianLanguage();
    this.addStyle();
    this.addCommand({
      id: "open-loans-view",
      name: this.tr("openLoansView"),
      callback: () => new LoansView(this.app, this).open()
    });
    this.addCommand({
      id: "add-new-loan",
      name: this.tr("addLoan"),
      callback: () => new LoanEditModal(this.app, this).open()
    });
    this.addRibbonIcon("dollar-sign", this.tr("pluginName"), () => {
      new LoansView(this.app, this).open();
    });
    this.addSettingTab(new LoansSettingTab(this.app, this));
    this.registerInterval(window.setInterval(() => this.checkOverduePayments(), 60 * 60 * 1e3));
  }
  async onunload() {
    await this.saveData();
  }
  addStyle() {
    const style = document.createElement("style");
    style.textContent = `
			.loans-plugin-container { padding: 20px; }
			.loans-overall-stats {
				display: grid;
				grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
				gap: 15px;
				margin: 20px 0;
				padding: 15px;
				background: var(--background-secondary);
				border-radius: 8px;
			}
			.loan-item {
				margin: 15px 0;
				padding: 15px;
				background: var(--background-secondary);
				border-radius: 8px;
				border-left: 4px solid var(--interactive-accent);
			}
			.progress-bar {
				height: 8px;
				background: var(--background-modifier-border);
				border-radius: 4px;
				margin: 10px 0;
				overflow: hidden;
			}
			.progress-fill {
				height: 100%;
				background: var(--interactive-accent);
				border-radius: 4px;
			}
			.loans-actions { display: flex; gap: 10px; margin: 20px 0; }
			.loans-actions button {
				padding: 8px 16px;
				background: var(--interactive-accent);
				color: var(--text-on-accent);
				border: none;
				border-radius: 4px;
				cursor: pointer;
			}
			.payment-status { padding: 4px 8px; border-radius: 4px; font-size: 12px; }
			.payment-status.pending { background: rgba(255,193,7,0.2); color: #ff9800; }
			.payment-status.paid { background: rgba(76,175,80,0.2); color: #4caf50; }
			.payment-status.overdue { background: rgba(244,67,54,0.2); color: #f44336; }
		`;
    document.head.appendChild(style);
  }
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data);
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async loadData() {
    try {
      const data = await this.app.vault.adapter.read(this.settings.storageFile);
      return JSON.parse(data);
    } catch (e) {
      return {};
    }
  }
  async saveData(data) {
    if (data) {
      await this.saveData(data);
    } else {
      const content = JSON.stringify({
        loans: this.loans,
        payments: this.payments,
        lastUpdated: new Date().toISOString()
      }, null, 2);
      await this.app.vault.adapter.write(this.settings.storageFile, content);
    }
  }
  // ==================== CRUD КРЕДИТОВ ====================
  addLoan(loan) {
    loan.id = "loan_" + Date.now();
    loan.createdAt = new Date().toISOString();
    loan.updatedAt = loan.createdAt;
    this.loans.push(loan);
    this.generatePayments(loan);
    this.saveData();
    new import_obsidian.Notice(this.tr("loanAdded", { name: loan.name }));
  }
  updateLoan(loan) {
    const idx = this.loans.findIndex((l) => l.id === loan.id);
    if (idx >= 0) {
      loan.updatedAt = new Date().toISOString();
      this.loans[idx] = loan;
      this.regeneratePayments(loan);
      this.saveData();
      new import_obsidian.Notice(this.tr("loanUpdated", { name: loan.name }));
    }
  }
  deleteLoan(loanId) {
    const loan = this.loans.find((l) => l.id === loanId);
    this.loans = this.loans.filter((l) => l.id !== loanId);
    this.payments = this.payments.filter((p) => p.loanId !== loanId);
    this.saveData();
    if (loan)
      new import_obsidian.Notice(this.tr("loanDeleted", { name: loan.name }));
  }
  // ==================== ГЕНЕРАЦИЯ ПЛАТЕЖЕЙ ====================
  generatePayments(loan) {
    const monthlyRate = loan.interestRate / 100 / 12;
    const payments = [];
    for (let i = 1; i <= loan.termMonths; i++) {
      const paymentDate = new Date(loan.startDate);
      paymentDate.setMonth(paymentDate.getMonth() + i);
      const dateStr = paymentDate.toISOString().split("T")[0];
      let amount = 0, principal = 0, interest = 0;
      if (loan.paymentType === "annuity") {
        const annuityCoeff = monthlyRate * Math.pow(1 + monthlyRate, loan.termMonths) / (Math.pow(1 + monthlyRate, loan.termMonths) - 1);
        amount = loan.totalAmount * annuityCoeff;
        interest = (loan.totalAmount - (i - 1) * (loan.totalAmount / loan.termMonths)) * monthlyRate;
        principal = amount - interest;
      } else {
        principal = loan.totalAmount / loan.termMonths;
        interest = (loan.totalAmount - (i - 1) * principal) * monthlyRate;
        amount = principal + interest;
      }
      payments.push({
        id: `payment_${loan.id}_${i}`,
        loanId: loan.id,
        date: dateStr,
        amount: Math.round(amount * 100) / 100,
        principal: Math.round(principal * 100) / 100,
        interest: Math.round(interest * 100) / 100,
        status: "pending",
        notes: `\u041F\u043B\u0430\u0442\u0435\u0436 ${i} \u0438\u0437 ${loan.termMonths}`
      });
    }
    this.payments.push(...payments);
  }
  regeneratePayments(loan) {
    this.payments = this.payments.filter((p) => p.loanId !== loan.id);
    this.generatePayments(loan);
  }
  // ==================== ОПЕРАЦИИ С ПЛАТЕЖАМИ ====================
  markPaymentAsPaid(paymentId, paidAmount, paidDate) {
    const payment = this.payments.find((p) => p.id === paymentId);
    if (payment) {
      payment.status = "paid";
      payment.paidAmount = paidAmount;
      payment.paidDate = paidDate;
      this.saveData();
      new import_obsidian.Notice(`\u041F\u043B\u0430\u0442\u0435\u0436 \u043E\u0442\u043C\u0435\u0447\u0435\u043D \u043A\u0430\u043A \u0432\u044B\u043F\u043E\u043B\u043D\u0435\u043D\u043D\u044B\u0439`);
    }
  }
  getPaymentsForLoan(loanId) {
    return this.payments.filter((p) => p.loanId === loanId).sort((a, b) => a.date.localeCompare(b.date));
  }
  // ==================== СТАТИСТИКА ====================
  getLoanStats(loanId) {
    const loan = this.loans.find((l) => l.id === loanId);
    if (!loan)
      throw new Error("\u041A\u0440\u0435\u0434\u0438\u0442 \u043D\u0435 \u043D\u0430\u0439\u0434\u0435\u043D");
    const loanPayments = this.getPaymentsForLoan(loanId);
    const paidPayments = loanPayments.filter((p) => p.status === "paid");
    const totalPaid = paidPayments.reduce((sum, p) => sum + (p.paidAmount || p.amount), 0);
    const totalPrincipal = paidPayments.reduce((sum, p) => sum + p.principal, 0);
    const remainingPrincipal = loan.totalAmount - totalPrincipal;
    const totalInterest = paidPayments.reduce((sum, p) => sum + p.interest, 0);
    const overpaid = totalPaid - (totalPrincipal + totalInterest);
    const nextPayment = loanPayments.find((p) => p.status === "pending");
    return {
      loan,
      totalPaid,
      remainingPrincipal,
      overpaid,
      nextPaymentDate: nextPayment == null ? void 0 : nextPayment.date,
      nextPaymentAmount: nextPayment == null ? void 0 : nextPayment.amount,
      progress: loan.totalAmount > 0 ? totalPrincipal / loan.totalAmount * 100 : 0
    };
  }
  getOverallStats() {
    let totalDebt = 0, totalPaid = 0, totalOverpaid = 0;
    this.loans.forEach((loan) => {
      const stats = this.getLoanStats(loan.id);
      totalDebt += stats.remainingPrincipal;
      totalPaid += stats.totalPaid;
      totalOverpaid += stats.overpaid;
    });
    return {
      totalLoans: this.loans.length,
      totalDebt,
      totalPaid,
      totalOverpaid,
      avgProgress: this.loans.length > 0 ? this.loans.reduce((sum, loan) => sum + this.getLoanStats(loan.id).progress, 0) / this.loans.length : 0
    };
  }
  // ==================== УПРАВЛЕНИЕ ВИДИМОСТЬЮ ====================
  toggleLoanHidden(loanId) {
    const loan = this.loans.find((l) => l.id === loanId);
    if (loan) {
      loan.hidden = !loan.hidden;
      this.saveData();
      new import_obsidian.Notice(loan.hidden ? "\u041A\u0440\u0435\u0434\u0438\u0442 \u0441\u043A\u0440\u044B\u0442" : "\u041A\u0440\u0435\u0434\u0438\u0442 \u043F\u043E\u043A\u0430\u0437\u0430\u043D");
    }
  }
  // ==================== ДОСРОЧНЫЙ ПЛАТЕЖ ====================
  makeEarlyRepayment(loanId, amount, date) {
    const loan = this.loans.find((l) => l.id === loanId);
    if (!loan)
      throw new Error("\u041A\u0440\u0435\u0434\u0438\u0442 \u043D\u0435 \u043D\u0430\u0439\u0434\u0435\u043D");
    const payment = {
      id: `early_${loanId}_${Date.now()}`,
      loanId,
      date,
      amount,
      principal: amount,
      // Вся сумма идет в основной долг
      interest: 0,
      status: "paid",
      paidAmount: amount,
      paidDate: date,
      notes: "\u0414\u043E\u0441\u0440\u043E\u0447\u043D\u043E\u0435 \u043F\u043E\u0433\u0430\u0448\u0435\u043D\u0438\u0435"
    };
    this.payments.push(payment);
    this.saveData();
    new import_obsidian.Notice(this.tr("paymentMarkedPaid"));
  }
  // ==================== ЛОКАЛИЗАЦИЯ ====================
  tr(key, params) {
    return t(key, this.language, params);
  }
  // ==================== ВСПОМОГАТЕЛЬНЫЕ МЕТОДЫ ====================
  checkOverduePayments() {
    if (!this.settings.showNotifications)
      return;
    const today = new Date().toISOString().split("T")[0];
    const overdue = this.payments.filter((p) => p.status === "pending" && p.date < today);
    if (overdue.length > 0) {
      new import_obsidian.Notice(`\u0412\u043D\u0438\u043C\u0430\u043D\u0438\u0435: \u0443 \u0432\u0430\u0441 ${overdue.length} \u043F\u0440\u043E\u0441\u0440\u043E\u0447\u0435\u043D\u043D\u044B\u0445 \u043F\u043B\u0430\u0442\u0435\u0436\u0435\u0439!`);
    }
  }
  calculateOptimalRepayment(availableAmount) {
    const loansWithStats = this.loans.map((loan) => ({
      loan,
      stats: this.getLoanStats(loan.id)
    })).filter((item) => item.stats.remainingPrincipal > 0).sort((a, b) => b.loan.interestRate - a.loan.interestRate);
    const result = [];
    let remaining = availableAmount;
    for (const item of loansWithStats) {
      if (remaining <= 0)
        break;
      const toRepay = Math.min(item.stats.remainingPrincipal, remaining);
      const savedInterest = toRepay * item.loan.interestRate / 100 / 12 * 6;
      result.push({
        loan: item.loan,
        amountToRepay: toRepay,
        savedInterest,
        newRemaining: item.stats.remainingPrincipal - toRepay
      });
      remaining -= toRepay;
    }
    return result;
  }
};
var LoanEditModal = class extends import_obsidian.Modal {
  constructor(app, plugin, loan) {
    super(app);
    this.plugin = plugin;
    this.loan = loan;
  }
  onOpen() {
    var _a, _b, _c, _d, _e, _f, _g, _h;
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: this.loan ? "\u0420\u0435\u0434\u0430\u043A\u0442\u0438\u0440\u043E\u0432\u0430\u0442\u044C \u043A\u0440\u0435\u0434\u0438\u0442" : "\u0414\u043E\u0431\u0430\u0432\u0438\u0442\u044C \u043D\u043E\u0432\u044B\u0439 \u043A\u0440\u0435\u0434\u0438\u0442" });
    const form = contentEl.createEl("form");
    this.createInput(form, "\u041D\u0430\u0437\u0432\u0430\u043D\u0438\u0435 \u043A\u0440\u0435\u0434\u0438\u0442\u0430", "text", "name", ((_a = this.loan) == null ? void 0 : _a.name) || "", true);
    this.createInput(form, "\u0421\u0443\u043C\u043C\u0430 \u043A\u0440\u0435\u0434\u0438\u0442\u0430", "number", "totalAmount", ((_b = this.loan) == null ? void 0 : _b.totalAmount.toString()) || "100000", true);
    this.createInput(form, "\u041F\u0440\u043E\u0446\u0435\u043D\u0442\u043D\u0430\u044F \u0441\u0442\u0430\u0432\u043A\u0430 (% \u0433\u043E\u0434.)", "number", "interestRate", ((_c = this.loan) == null ? void 0 : _c.interestRate.toString()) || "10", true);
    this.createInput(form, "\u0421\u0440\u043E\u043A (\u043C\u0435\u0441\u044F\u0446\u0435\u0432)", "number", "termMonths", ((_d = this.loan) == null ? void 0 : _d.termMonths.toString()) || "12", true);
    this.createInput(form, "\u0414\u0430\u0442\u0430 \u043D\u0430\u0447\u0430\u043B\u0430", "date", "startDate", ((_e = this.loan) == null ? void 0 : _e.startDate) || new Date().toISOString().split("T")[0], true);
    const typeGroup = form.createDiv();
    typeGroup.createEl("label", { text: "\u0422\u0438\u043F \u043F\u043B\u0430\u0442\u0435\u0436\u0430" });
    const select = typeGroup.createEl("select", { attr: { name: "paymentType" } });
    select.createEl("option", { value: "annuity", text: "\u0410\u043D\u043D\u0443\u0438\u0442\u0435\u0442\u043D\u044B\u0439" });
    select.createEl("option", { value: "differentiated", text: "\u0414\u0438\u0444\u0444\u0435\u0440\u0435\u043D\u0446\u0438\u0440\u043E\u0432\u0430\u043D\u043D\u044B\u0439" });
    if ((_f = this.loan) == null ? void 0 : _f.paymentType) {
      select.value = this.loan.paymentType;
    }
    this.createInput(form, "\u0412\u0430\u043B\u044E\u0442\u0430", "text", "currency", ((_g = this.loan) == null ? void 0 : _g.currency) || this.plugin.settings.defaultCurrency, true);
    const notesGroup = form.createDiv();
    notesGroup.createEl("label", { text: "\u0417\u0430\u043C\u0435\u0442\u043A\u0438" });
    const textarea = notesGroup.createEl("textarea", { attr: { name: "notes", rows: "3" } });
    textarea.setText(((_h = this.loan) == null ? void 0 : _h.notes) || "");
    const buttons = form.createDiv();
    const submit = buttons.createEl("button", { text: "\u0421\u043E\u0445\u0440\u0430\u043D\u0438\u0442\u044C", attr: { type: "submit" } });
    submit.addClass("mod-cta");
    if (this.loan) {
      const deleteBtn = buttons.createEl("button", { text: "\u0423\u0434\u0430\u043B\u0438\u0442\u044C" });
      deleteBtn.addEventListener("click", () => {
        if (confirm("\u0423\u0434\u0430\u043B\u0438\u0442\u044C \u044D\u0442\u043E\u0442 \u043A\u0440\u0435\u0434\u0438\u0442?")) {
          this.plugin.deleteLoan(this.loan.id);
          this.close();
        }
      });
    }
    const cancel = buttons.createEl("button", { text: "\u041E\u0442\u043C\u0435\u043D\u0430" });
    cancel.addEventListener("click", () => this.close());
    form.addEventListener("submit", (e) => {
      var _a2, _b2;
      e.preventDefault();
      const formData = new FormData(form);
      const loan = {
        id: ((_a2 = this.loan) == null ? void 0 : _a2.id) || "",
        name: formData.get("name"),
        totalAmount: parseFloat(formData.get("totalAmount")),
        interestRate: parseFloat(formData.get("interestRate")),
        termMonths: parseInt(formData.get("termMonths")),
        startDate: formData.get("startDate"),
        paymentType: formData.get("paymentType"),
        currency: formData.get("currency"),
        notes: formData.get("notes"),
        createdAt: ((_b2 = this.loan) == null ? void 0 : _b2.createdAt) || "",
        updatedAt: ""
      };
      if (this.loan) {
        loan.id = this.loan.id;
        loan.createdAt = this.loan.createdAt;
        this.plugin.updateLoan(loan);
      } else {
        this.plugin.addLoan(loan);
      }
      this.close();
    });
  }
  createInput(parent, label, type, name, value, required = false) {
    const group = parent.createDiv();
    group.createEl("label", { text: label });
    const input = group.createEl("input", { attr: { type, name, value } });
    if (required)
      input.setAttribute("required", "");
    return input;
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var MarkPaymentModal = class extends import_obsidian.Modal {
  constructor(app, plugin, paymentId) {
    super(app);
    this.plugin = plugin;
    this.paymentId = paymentId;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "\u041E\u0442\u043C\u0435\u0442\u0438\u0442\u044C \u043F\u043B\u0430\u0442\u0435\u0436 \u043A\u0430\u043A \u0432\u044B\u043F\u043E\u043B\u043D\u0435\u043D\u043D\u044B\u0439" });
    if (!this.paymentId) {
      contentEl.createEl("p", { text: "\u041F\u043B\u0430\u0442\u0435\u0436 \u043D\u0435 \u0432\u044B\u0431\u0440\u0430\u043D." });
      return;
    }
    const payment = this.plugin.payments.find((p) => p.id === this.paymentId);
    if (!payment) {
      contentEl.createEl("p", { text: "\u041F\u043B\u0430\u0442\u0435\u0436 \u043D\u0435 \u043D\u0430\u0439\u0434\u0435\u043D." });
      return;
    }
    const loan = this.plugin.loans.find((l) => l.id === payment.loanId);
    const loanName = loan ? loan.name : "\u041D\u0435\u0438\u0437\u0432\u0435\u0441\u0442\u043D\u044B\u0439 \u043A\u0440\u0435\u0434\u0438\u0442";
    contentEl.createEl("p", { text: `\u041A\u0440\u0435\u0434\u0438\u0442: ${loanName}` });
    contentEl.createEl("p", { text: `\u0414\u0430\u0442\u0430 \u043F\u043B\u0430\u0442\u0435\u0436\u0430: ${payment.date}` });
    contentEl.createEl("p", { text: `\u041F\u043B\u0430\u043D\u0438\u0440\u0443\u0435\u043C\u0430\u044F \u0441\u0443\u043C\u043C\u0430: ${payment.amount.toFixed(2)}` });
    const form = contentEl.createEl("form");
    const amountGroup = form.createDiv();
    amountGroup.createEl("label", { text: "\u0424\u0430\u043A\u0442\u0438\u0447\u0435\u0441\u043A\u0438 \u0443\u043F\u043B\u0430\u0447\u0435\u043D\u043D\u0430\u044F \u0441\u0443\u043C\u043C\u0430" });
    const amountInput = amountGroup.createEl("input", { attr: { type: "number", step: "0.01", value: payment.amount.toString() } });
    const dateGroup = form.createDiv();
    dateGroup.createEl("label", { text: "\u0414\u0430\u0442\u0430 \u043E\u043F\u043B\u0430\u0442\u044B" });
    const dateInput = dateGroup.createEl("input", { attr: { type: "date", value: new Date().toISOString().split("T")[0] } });
    const button = form.createEl("button", { text: "\u041E\u0442\u043C\u0435\u0442\u0438\u0442\u044C \u043A\u0430\u043A \u0432\u044B\u043F\u043E\u043B\u043D\u0435\u043D\u043D\u044B\u0439", attr: { type: "submit" } });
    button.addClass("mod-cta");
    form.addEventListener("submit", (e) => {
      e.preventDefault();
      const paidAmount = parseFloat(amountInput.value);
      const paidDate = dateInput.value;
      if (paidAmount <= 0) {
        new import_obsidian.Notice("\u0421\u0443\u043C\u043C\u0430 \u0434\u043E\u043B\u0436\u043D\u0430 \u0431\u044B\u0442\u044C \u043F\u043E\u043B\u043E\u0436\u0438\u0442\u0435\u043B\u044C\u043D\u043E\u0439");
        return;
      }
      this.plugin.markPaymentAsPaid(this.paymentId, paidAmount, paidDate);
      this.close();
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var PaymentsView = class extends import_obsidian.Modal {
  constructor(app, plugin, loan) {
    super(app);
    this.plugin = plugin;
    this.loan = loan;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: `\u041F\u043B\u0430\u0442\u0435\u0436\u0438: ${this.loan.name}` });
    const earlyBtn = contentEl.createEl("button", { text: "\u{1F4B3} \u0414\u043E\u0441\u0440\u043E\u0447\u043D\u044B\u0439 \u043F\u043B\u0430\u0442\u0435\u0436" });
    earlyBtn.style.marginBottom = "15px";
    earlyBtn.addEventListener("click", () => {
      new EarlyRepaymentModal(this.app, this.plugin, this.loan).open();
    });
    const payments = this.plugin.getPaymentsForLoan(this.loan.id);
    if (payments.length === 0) {
      contentEl.createEl("p", { text: "\u041D\u0435\u0442 \u043F\u043B\u0430\u0442\u0435\u0436\u0435\u0439 \u0434\u043B\u044F \u044D\u0442\u043E\u0433\u043E \u043A\u0440\u0435\u0434\u0438\u0442\u0430." });
      return;
    }
    const table = contentEl.createEl("table");
    const header = table.createEl("thead");
    const headerRow = header.createEl("tr");
    ["\u0414\u0430\u0442\u0430", "\u0421\u0443\u043C\u043C\u0430", "\u041E\u0441\u043D\u043E\u0432\u043D\u043E\u0439 \u0434\u043E\u043B\u0433", "\u041F\u0440\u043E\u0446\u0435\u043D\u0442\u044B", "\u0421\u0442\u0430\u0442\u0443\u0441", "\u0414\u0435\u0439\u0441\u0442\u0432\u0438\u044F"].forEach((text) => {
      headerRow.createEl("th", { text });
    });
    const body = table.createEl("tbody");
    payments.forEach((p) => {
      const row = body.createEl("tr");
      row.createEl("td", { text: p.date });
      row.createEl("td", { text: p.amount.toFixed(2) });
      row.createEl("td", { text: p.principal.toFixed(2) });
      row.createEl("td", { text: p.interest.toFixed(2) });
      const statusCell = row.createEl("td");
      const statusSpan = statusCell.createEl("span", { text: p.status, cls: `payment-status ${p.status}` });
      const actionsCell = row.createEl("td");
      if (p.status === "pending") {
        const markBtn = actionsCell.createEl("button", { text: "\u041E\u0442\u043C\u0435\u0442\u0438\u0442\u044C \u043E\u043F\u043B\u0430\u0442\u0443" });
        markBtn.addEventListener("click", () => {
          new MarkPaymentModal(this.app, this.plugin, p.id).open();
          this.close();
        });
      } else {
        actionsCell.createEl("span", { text: `\u041E\u043F\u043B\u0430\u0447\u0435\u043D ${p.paidDate || p.date}` });
      }
    });
    const buttonRow = contentEl.createDiv({ cls: "payments-actions" });
    const backBtn = buttonRow.createEl("button", { text: "\u041D\u0430\u0437\u0430\u0434" });
    backBtn.addEventListener("click", () => this.close());
    const refreshBtn = buttonRow.createEl("button", { text: "\u{1F504} \u041E\u0431\u043D\u043E\u0432\u0438\u0442\u044C" });
    refreshBtn.addEventListener("click", () => {
      this.onClose();
      this.onOpen();
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var EarlyRepaymentModal = class extends import_obsidian.Modal {
  constructor(app, plugin, loan) {
    super(app);
    this.plugin = plugin;
    this.loan = loan;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    const stats = this.plugin.getLoanStats(this.loan.id);
    contentEl.createEl("h2", { text: `\u0414\u043E\u0441\u0440\u043E\u0447\u043D\u044B\u0439 \u043F\u043B\u0430\u0442\u0435\u0436: ${this.loan.name}` });
    contentEl.createEl("p", { text: `\u041E\u0441\u0442\u0430\u0442\u043E\u043A \u0434\u043E\u043B\u0433\u0430: ${stats.remainingPrincipal.toFixed(2)} ${this.loan.currency}` });
    const form = contentEl.createEl("form");
    const amountGroup = form.createDiv();
    amountGroup.createEl("label", { text: "\u0421\u0443\u043C\u043C\u0430 \u0434\u043E\u0441\u0440\u043E\u0447\u043D\u043E\u0433\u043E \u043F\u043E\u0433\u0430\u0448\u0435\u043D\u0438\u044F" });
    const amountInput = amountGroup.createEl("input", {
      attr: { type: "number", step: "0.01", min: "0", max: stats.remainingPrincipal.toString(), value: stats.remainingPrincipal.toString() }
    });
    const dateGroup = form.createDiv();
    dateGroup.createEl("label", { text: "\u0414\u0430\u0442\u0430 \u043F\u043E\u0433\u0430\u0448\u0435\u043D\u0438\u044F" });
    const dateInput = dateGroup.createEl("input", {
      attr: { type: "date", value: new Date().toISOString().split("T")[0] }
    });
    const button = form.createEl("button", { text: "\u0412\u043D\u0435\u0441\u0442\u0438 \u0434\u043E\u0441\u0440\u043E\u0447\u043D\u044B\u0439 \u043F\u043B\u0430\u0442\u0435\u0436", attr: { type: "submit" } });
    button.addClass("mod-cta");
    form.addEventListener("submit", (e) => {
      e.preventDefault();
      const amount = parseFloat(amountInput.value);
      const date = dateInput.value;
      if (amount <= 0) {
        new import_obsidian.Notice("\u0421\u0443\u043C\u043C\u0430 \u0434\u043E\u043B\u0436\u043D\u0430 \u0431\u044B\u0442\u044C \u043F\u043E\u043B\u043E\u0436\u0438\u0442\u0435\u043B\u044C\u043D\u043E\u0439");
        return;
      }
      if (amount > stats.remainingPrincipal) {
        new import_obsidian.Notice("\u0421\u0443\u043C\u043C\u0430 \u043D\u0435 \u043C\u043E\u0436\u0435\u0442 \u043F\u0440\u0435\u0432\u044B\u0448\u0430\u0442\u044C \u043E\u0441\u0442\u0430\u0442\u043E\u043A \u0434\u043E\u043B\u0433\u0430");
        return;
      }
      this.plugin.makeEarlyRepayment(this.loan.id, amount, date);
      this.close();
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var LoansView = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("loans-plugin-container");
    contentEl.createEl("h1", { text: "\u0423\u0447\u0435\u0442 \u043A\u0440\u0435\u0434\u0438\u0442\u043E\u0432" });
    const overall = this.plugin.getOverallStats();
    const statsDiv = contentEl.createDiv({ cls: "loans-overall-stats" });
    statsDiv.createEl("div", { text: `\u041A\u0440\u0435\u0434\u0438\u0442\u043E\u0432: ${overall.totalLoans}` });
    statsDiv.createEl("div", { text: `\u041E\u0431\u0449\u0438\u0439 \u0434\u043E\u043B\u0433: ${overall.totalDebt.toFixed(2)}` });
    statsDiv.createEl("div", { text: `\u0412\u044B\u043F\u043B\u0430\u0447\u0435\u043D\u043E: ${overall.totalPaid.toFixed(2)}` });
    statsDiv.createEl("div", { text: `\u041F\u0435\u0440\u0435\u043F\u043B\u0430\u0442\u0430: ${overall.totalOverpaid.toFixed(2)}` });
    contentEl.createEl("h2", { text: "\u0412\u0430\u0448\u0438 \u043A\u0440\u0435\u0434\u0438\u0442\u044B" });
    const visibleLoans = this.plugin.loans.filter((loan) => !loan.hidden);
    if (visibleLoans.length === 0) {
      contentEl.createEl("p", { text: "\u041D\u0435\u0442 \u0430\u043A\u0442\u0438\u0432\u043D\u044B\u0445 \u043A\u0440\u0435\u0434\u0438\u0442\u043E\u0432. \u0414\u043E\u0431\u0430\u0432\u044C\u0442\u0435 \u043D\u043E\u0432\u044B\u0439 \u0438\u043B\u0438 \u043F\u043E\u043A\u0430\u0436\u0438\u0442\u0435 \u0441\u043A\u0440\u044B\u0442\u044B\u0435." });
    } else {
      visibleLoans.forEach((loan) => {
        const stats = this.plugin.getLoanStats(loan.id);
        const div = contentEl.createDiv({ cls: "loan-item" });
        div.createEl("h3", { text: loan.name });
        div.createEl("p", { text: `\u0421\u0443\u043C\u043C\u0430: ${loan.totalAmount} ${loan.currency} | \u0421\u0442\u0430\u0432\u043A\u0430: ${loan.interestRate}%` });
        div.createEl("p", { text: `\u041E\u0441\u0442\u0430\u0442\u043E\u043A: ${stats.remainingPrincipal.toFixed(2)} | \u041F\u0440\u043E\u0433\u0440\u0435\u0441\u0441: ${stats.progress.toFixed(1)}%` });
        const progressBar = div.createDiv({ cls: "progress-bar" });
        const progressFill = progressBar.createDiv({ cls: "progress-fill" });
        progressFill.style.width = `${Math.min(stats.progress, 100)}%`;
        const btnGroup = div.createDiv();
        const editBtn = btnGroup.createEl("button", { text: "\u0420\u0435\u0434\u0430\u043A\u0442\u0438\u0440\u043E\u0432\u0430\u0442\u044C" });
        editBtn.addEventListener("click", () => {
          this.close();
          new LoanEditModal(this.app, this.plugin, loan).open();
        });
        const paymentsBtn = btnGroup.createEl("button", { text: "\u041F\u043B\u0430\u0442\u0435\u0436\u0438" });
        paymentsBtn.addEventListener("click", () => {
          new PaymentsView(this.app, this.plugin, loan).open();
        });
        if (stats.progress >= 100) {
          const hideBtn = btnGroup.createEl("button", { text: "\u0421\u043A\u0440\u044B\u0442\u044C" });
          hideBtn.addEventListener("click", () => {
            this.plugin.toggleLoanHidden(loan.id);
            this.onClose();
            this.onOpen();
          });
        }
      });
    }
    const hiddenLoans = this.plugin.loans.filter((loan) => loan.hidden);
    if (hiddenLoans.length > 0) {
      contentEl.createEl("h3", { text: "\u0421\u043A\u0440\u044B\u0442\u044B\u0435 \u043A\u0440\u0435\u0434\u0438\u0442\u044B" });
      hiddenLoans.forEach((loan) => {
        const stats = this.plugin.getLoanStats(loan.id);
        const div = contentEl.createDiv({ cls: "loan-item hidden" });
        div.style.opacity = "0.7";
        div.createEl("h4", { text: `\u{1F4CC} ${loan.name} (\u0441\u043A\u0440\u044B\u0442)` });
        div.createEl("p", { text: `\u041F\u0440\u043E\u0433\u0440\u0435\u0441\u0441: ${stats.progress.toFixed(1)}%` });
        const showBtn = div.createEl("button", { text: "\u041F\u043E\u043A\u0430\u0437\u0430\u0442\u044C" });
        showBtn.addEventListener("click", () => {
          this.plugin.toggleLoanHidden(loan.id);
          this.onClose();
          this.onOpen();
        });
      });
    }
    const actions = contentEl.createDiv({ cls: "loans-actions" });
    const addBtn = actions.createEl("button", { text: "\u2795 \u0414\u043E\u0431\u0430\u0432\u0438\u0442\u044C \u043A\u0440\u0435\u0434\u0438\u0442" });
    addBtn.addEventListener("click", () => {
      this.close();
      new LoanEditModal(this.app, this.plugin).open();
    });
    const calcBtn = actions.createEl("button", { text: "\u{1F9EE} \u041A\u0430\u043B\u044C\u043A\u0443\u043B\u044F\u0442\u043E\u0440 \u043F\u043E\u0433\u0430\u0448\u0435\u043D\u0438\u044F" });
    calcBtn.addEventListener("click", () => {
      new RepaymentCalculatorModal(this.app, this.plugin).open();
    });
    const refreshBtn = actions.createEl("button", { text: "\u{1F504} \u041E\u0431\u043D\u043E\u0432\u0438\u0442\u044C" });
    refreshBtn.addEventListener("click", () => {
      this.onClose();
      this.onOpen();
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var RepaymentCalculatorModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "\u041A\u0430\u043B\u044C\u043A\u0443\u043B\u044F\u0442\u043E\u0440 \u0432\u044B\u0433\u043E\u0434\u043D\u043E\u0433\u043E \u043F\u043E\u0433\u0430\u0448\u0435\u043D\u0438\u044F" });
    contentEl.createEl("p", { text: "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u0441\u0443\u043C\u043C\u0443, \u043A\u043E\u0442\u043E\u0440\u0443\u044E \u043C\u043E\u0436\u0435\u0442\u0435 \u043D\u0430\u043F\u0440\u0430\u0432\u0438\u0442\u044C \u043D\u0430 \u0434\u043E\u0441\u0440\u043E\u0447\u043D\u043E\u0435 \u043F\u043E\u0433\u0430\u0448\u0435\u043D\u0438\u0435:" });
    const input = contentEl.createEl("input", {
      attr: { type: "number", placeholder: "\u0421\u0443\u043C\u043C\u0430", value: "10000" }
    });
    input.style.marginRight = "10px";
    const button = contentEl.createEl("button", { text: "\u0420\u0430\u0441\u0441\u0447\u0438\u0442\u0430\u0442\u044C" });
    button.addClass("mod-cta");
    const resultsDiv = contentEl.createDiv();
    button.addEventListener("click", () => {
      const amount = parseFloat(input.value);
      if (amount <= 0) {
        new import_obsidian.Notice("\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u043F\u043E\u043B\u043E\u0436\u0438\u0442\u0435\u043B\u044C\u043D\u0443\u044E \u0441\u0443\u043C\u043C\u0443");
        return;
      }
      const recommendations = this.plugin.calculateOptimalRepayment(amount);
      resultsDiv.empty();
      if (recommendations.length === 0) {
        resultsDiv.createEl("p", { text: "\u041D\u0435\u0442 \u0430\u043A\u0442\u0438\u0432\u043D\u044B\u0445 \u043A\u0440\u0435\u0434\u0438\u0442\u043E\u0432 \u0434\u043B\u044F \u043F\u043E\u0433\u0430\u0448\u0435\u043D\u0438\u044F." });
        return;
      }
      resultsDiv.createEl("h3", { text: "\u0420\u0435\u043A\u043E\u043C\u0435\u043D\u0434\u0430\u0446\u0438\u0438:" });
      recommendations.forEach((rec) => {
        const div = resultsDiv.createDiv();
        div.createEl("p", {
          text: `\u041A\u0440\u0435\u0434\u0438\u0442 "${rec.loan.name}": \u043F\u043E\u0433\u0430\u0441\u0438\u0442\u044C ${rec.amountToRepay.toFixed(2)} ${rec.loan.currency}`
        });
        div.createEl("p", {
          text: `\u042D\u043A\u043E\u043D\u043E\u043C\u0438\u044F \u043D\u0430 \u043F\u0440\u043E\u0446\u0435\u043D\u0442\u0430\u0445: ~${rec.savedInterest.toFixed(2)} ${rec.loan.currency}`
        });
      });
    });
    button.click();
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var LoansSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u041D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0438 \u043F\u043B\u0430\u0433\u0438\u043D\u0430 \u0443\u0447\u0435\u0442\u0430 \u043A\u0440\u0435\u0434\u0438\u0442\u043E\u0432" });
    new import_obsidian.Setting(containerEl).setName("\u0424\u0430\u0439\u043B \u0445\u0440\u0430\u043D\u0435\u043D\u0438\u044F \u0434\u0430\u043D\u043D\u044B\u0445").setDesc("JSON \u0444\u0430\u0439\u043B, \u0433\u0434\u0435 \u0445\u0440\u0430\u043D\u044F\u0442\u0441\u044F \u0434\u0430\u043D\u043D\u044B\u0435 \u043E \u043A\u0440\u0435\u0434\u0438\u0442\u0430\u0445").addText((text) => text.setPlaceholder("loans-data.json").setValue(this.plugin.settings.storageFile).onChange(async (value) => {
      this.plugin.settings.storageFile = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u0412\u0430\u043B\u044E\u0442\u0430 \u043F\u043E \u0443\u043C\u043E\u043B\u0447\u0430\u043D\u0438\u044E").setDesc("\u0412\u0430\u043B\u044E\u0442\u0430 \u0434\u043B\u044F \u043D\u043E\u0432\u044B\u0445 \u043A\u0440\u0435\u0434\u0438\u0442\u043E\u0432 (RUB, USD, EUR \u0438 \u0442.\u0434.)").addText((text) => text.setPlaceholder("RUB").setValue(this.plugin.settings.defaultCurrency).onChange(async (value) => {
      this.plugin.settings.defaultCurrency = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u0423\u0432\u0435\u0434\u043E\u043C\u043B\u0435\u043D\u0438\u044F").setDesc("\u041F\u043E\u043A\u0430\u0437\u044B\u0432\u0430\u0442\u044C \u0443\u0432\u0435\u0434\u043E\u043C\u043B\u0435\u043D\u0438\u044F \u043E \u043F\u0440\u043E\u0441\u0440\u043E\u0447\u0435\u043D\u043D\u044B\u0445 \u043F\u043B\u0430\u0442\u0435\u0436\u0430\u0445").addToggle((toggle) => toggle.setValue(this.plugin.settings.showNotifications).onChange(async (value) => {
      this.plugin.settings.showNotifications = value;
      await this.plugin.saveSettings();
    }));
  }
};
